-- ======== Generated By Sqlx ========
-- https://github.com/taojy123/sqlx

SELECT
    id,
    'pro002' AS product_no,
    mash_contract_no,
            1 as is_a,
            0 as is_more,
    1_a as mark
FROM
    account_check
LEFT JOIN
    (
        SELECT
            mash_contract_no,
            max(unique_no) AS unique_no,
            max(apply_no) AS apply_no
        FROM
            loan_front_manager.mf_business_apply
        GROUP BY
            mash_contract_no
    ) AS mash_apply_mapping
ON mash_apply_mapping.mash_contract_no = account_check.contract_no
WHERE
    unique_no IS NOT NULL
UNION ALL
    SELECT
        *, NULL AS mash_contract_no
    FROM
        mf_business_loan_apply_log
SELECT
    id,
    'pro002' AS product_no,
    mash_contract_no,
            1 as is_more,
    2_b as mark
FROM
    account_check
LEFT JOIN
    (
        SELECT
            mash_contract_no,
            max(unique_no) AS unique_no,
            max(apply_no) AS apply_no
        FROM
            loan_front_manager.mf_business_apply
        GROUP BY
            mash_contract_no
    ) AS mash_apply_mapping
ON mash_apply_mapping.mash_contract_no = account_check.contract_no
WHERE
    unique_no IS NOT NULL
UNION ALL
    SELECT
        *, NULL AS mash_contract_no
    FROM
        mf_business_loan_apply_log
SELECT
    id,
    'pro002' AS product_no,
    mash_contract_no,
            1 as is_more,
    3_c as mark
FROM
    account_check
LEFT JOIN
    (
        SELECT
            mash_contract_no,
            max(unique_no) AS unique_no,
            max(apply_no) AS apply_no
        FROM
            loan_front_manager.mf_business_apply
        GROUP BY
            mash_contract_no
    ) AS mash_apply_mapping
ON mash_apply_mapping.mash_contract_no = account_check.contract_no
WHERE
    unique_no IS NOT NULL
UNION ALL
    SELECT
        *, NULL AS mash_contract_no
    FROM
        mf_business_loan_apply_log
